name: trackasia_gl_workspace

packages:
  - scripts
  - trackasia_gl*

scripts:
  test:
    description: Run all tests
    run: |
      set -e
      melos test:io
      melos test:web

  test:io:
    description: Run IO tests
    exec: flutter test
    packageFilters:
      scope: trackasia_gl_platform_interface

  test:web:
    description: Run Web tests
    exec: flutter test --platform chrome
    packageFilters:
      scope: trackasia_gl_platform_interface
