name: trackasia_gl_web
description: Web platform implementation of trackasia_gl. This package is only intended to be used by the trackasia_gl package.
version: 2.0.0
repository: https://github.com/trackasia/flutter-trackasia-gl
issue_tracker: https://github.com/trackasia/flutter-trackasia-gl/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: TrackAsiaMapPlugin
        fileName: trackasia_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image: ^4.0.17
  js: ">=0.6.7 <0.8.0"
  trackasia_gl_platform_interface: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  very_good_analysis: ^5.0.0

platforms:
  web:
