name: trackasia_gl_platform_interface
description: A common platform interface for the trackasia_gl plugin. This package is only intended to be used by the trackasia_gl package.
version: 2.0.0
repository: https://github.com/trackasia/flutter-trackasia-gl
issue_tracker: https://github.com/trackasia/flutter-trackasia-gl/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  very_good_analysis: ^5.0.0
