name: trackasia_gl_platform_interface
description: A common platform interface for the trackasia_gl plugin. This package is only intended to be used by the trackasia_gl package.
version: 2.0.1
repository: https://github.com/track-asia/flutter-trackasia-gl
issue_tracker: https://github.com/track-asia/flutter-trackasia-gl/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0
