name: trackasia_gl
description: A Flutter plugin for integrating TrackAsia Maps inside a Flutter application on Android, iOS and web platforms.
version: 2.0.3
repository: https://github.com/track-asia/flutter-trackasia-gl
issue_tracker: https://github.com/track-asia/flutter-trackasia-gl/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  trackasia_gl_platform_interface: ^2.0.1
  # trackasia_gl_platform_interface:
  #   path: ../trackasia_gl_platform_interface
  trackasia_gl_web: ^2.0.1
  # trackasia_gl_web:
  #   path: ../trackasia_gl_web

dev_dependencies:
  very_good_analysis: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.trackasia.trackasiagl
        pluginClass: TrackAsiaMapsPlugin
      ios:
        pluginClass: TrackAsiaMapsPlugin
      web:
        default_package: trackasia_gl_web

platforms:
  android:
  ios:
  web:
